### ISSUE TITLE
First attempt at a static visualization

### ISSUE THREAD

**Issue by wcornwell** [coreytcallaghan/eBirder-visualizations#1]

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/28606458-7d0f194e-721a-11e7-976a-d6ef111e154e.png)
first column is number of species total in the world.  Second one is number seen by that particular observer

thoughts?  @coreytcallaghan

**Comment by wcornwell** [comment]
family-level gets a bit hard to see:

![image](https://user-images.githubusercontent.com/5534161/28606563-f6fbe840-721a-11e7-9496-95367f14e657.png)

**Comment by wcornwell** [comment]
and radial will take a while to get to work with tip labels, but it looks pretty:

![image](https://user-images.githubusercontent.com/5534161/28606591-19f37552-721b-11e7-8576-c26544bccb40.png)

**Comment by coreytcallaghan** [comment]
yes, looks good!

Is that your bird data? In the second column.

**Comment by wcornwell** [comment]
no i just divided by 2.  can you upload your life list, and I'll use yours...

**Comment by coreytcallaghan** [comment]
Yeah. just did. But have to filter it first.

Two minutes....

**Comment by coreytcallaghan** [comment]
Uploaded now. But see the script that is example_phylogeny_calculation. Then you just need to apply those filters and that is my life list.

The filters are necessary because the "COMMON_NAME" column is odd and includes a bunch of stuff! 'spuh/slashes/groups/forms/subspecies/species'. Its all really complicated how they do it.

Another problem that I realized is that this 'life list' downloaded from the eBird basic dataset only includes 1185 species. It should include 1191. But, 6 records weren't 'accepted' into the eBird database, apparently....

So, will have to see if there is a way to get that without downloading your personal data. Because down the road, it will be critical to download from the main dataset. Might be able to include unvetted data as well.

**Comment by coreytcallaghan** [comment]
The radial looks awesome!

Orders looks good, but I would imagine most people would much prefer to see their family diversity.

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/28607228-39173ac4-721e-11e7-8c97-e0213e443cb3.png)

**Comment by coreytcallaghan** [comment]
That's sick!

It is an interesting plotting problem, mainly because the differentiation in species/family is so great! There are lots of families with just a couple species in them.

Imagine a birder being able to look at a site with all of this information. It would be wicked!

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/28607656-3419cb34-7220-11e7-8d0a-78d6559230e0.png)

**Comment by coreytcallaghan** [comment]
So, I've 'finished' a couple of families??

**Comment by wcornwell** [comment]
Anseranatidae (Magpie Goose) | 1.000000000
Aramidae (Limpkin) | 1.000000000
Corcoracidae (White-winged Chough and Apostlebird) | 1.000000000
Falcunculidae (Shrike-tit) | 1.000000000
Pandionidae (Osprey) | 1.000000000
Peucedramidae (Olive Warbler) | 1.000000000
Steatornithidae (Oilbird) | 1.000000000

**Comment by wcornwell** [comment]
Ptiliogonatidae (Silky-flycatchers) | 0.750000000
Bombycillidae (Waxwings) | 0.666666667
Calcariidae (Longspurs and Snow Buntings) | 0.666666667
Stercorariidae (Skuas and Jaegers) | 0.571428571
Anhingidae (Anhingas) | 0.500000000
Menuridae (Lyrebirds) | 0.500000000
Pardalotidae (Pardalotes) | 0.500000000

**Comment by coreytcallaghan** [comment]
Ha! I've got lots of work to do!

**Comment by coreytcallaghan** [comment]
I think we've moved past this a bit... so closing this issue.
